# Generated by Django 4.2.3 on 2023-07-25 07:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                ("txid", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
                (
                    "created_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 25, 10, 42, 51, 745049),
                        editable=False,
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 25, 10, 47, 51, 745049),
                        editable=False,
                    ),
                ),
                (
                    "ref",
                    models.CharField(default=uuid.uuid4, max_length=150, unique=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[(1, "Pending"), (2, "Done")], default=1, max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
