# Generated by Django 4.2.3 on 2023-07-25 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="network",
            field=models.CharField(
                choices=[(1, "TRC20"), (2, "BEP20")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 10, 44, 29, 304134),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 10, 49, 29, 304134),
                editable=False,
            ),
        ),
    ]
