# Generated by Django 4.2.3 on 2023-07-25 07:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_transaction_network_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice_number",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 10, 49, 10, 310521),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 10, 54, 10, 310521),
                editable=False,
            ),
        ),
    ]
