# Generated by Django 4.2.3 on 2023-07-25 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_transaction_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 14, 48, 28, 162536),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 14, 53, 28, 162536),
                editable=False,
            ),
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 25, 14, 48, 28, 162536),
                        editable=False,
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.wallet"
                    ),
                ),
            ],
        ),
    ]
