# Generated by Django 4.2.3 on 2023-07-25 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 15, 34, 8, 845798),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 15, 34, 8, 845798),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 15, 39, 8, 845798),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                choices=[(1, "Pending"), (2, "Done"), (3, "Failed")],
                default=1,
                max_length=1,
            ),
        ),
    ]
