# Generated by Django 4.2.3 on 2023-07-25 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_receiver_update_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="network",
            field=models.CharField(
                choices=[(1, "TRC20"), (2, "BEP20")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receiver",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 18, 30, 41, 789853),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 18, 30, 41, 788844),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 18, 35, 41, 788844),
                editable=False,
            ),
        ),
    ]
